name: Build Windows EXE for Streamlit App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe with PyInstaller
        run: |
          pyinstaller --onefile --name repartition_stage_enm --copy-metadata streamlit --additional-hooks-dir=./hooks --add-data "config\\parameters.json;config" --add-data "app;app" repartition_enm.py --clean

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repartition_stage_enm
          path: dist/repartition_stage_enm.exe

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/repartition_stage_enm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
